services:
    database_manager:
        image: adminer:latest
        ports:
            - "8080:8080"
        depends_on:
            - database
        networks:
            - my_network

    database:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - my_network

networks:
    my_network:
        driver: bridge
